### ISSUE TITLE
After login, the welcome message always: Welcome, Jane

### ISSUE THREAD

**Issue by davidnhtd** [WomenPlusPlus/deploy-impact-21-inzone-b#102]
![image](https://user-images.githubusercontent.com/4864420/140816388-4c31c475-6a7d-438f-9eac-f31d8b22efd8.png)

**Comment by davidnhtd** [comment]
@patricijab  @EzequiasCalvo FYI

**Comment by EzequiasCalvo** [comment]
I solved on branch fix-modal. Now its already pushed and merged
