### ISSUE TITLE
After Signup flow, Approval Message screen missing (since Admins need to approve any new account)

### ISSUE THREAD

**Issue by simoparaschi** [WomenPlusPlus/deploy-impact-21-inzone-b#116]
Check Figma to view the design if necessary

**Comment by davidnhtd** [comment]
Will mark this as "wont do" due to time constraints for the final presentation

**Comment by davidnhtd** [comment]
Reopened this because @patricijab is working on it

**Comment by davidnhtd** [comment]
@patricijab on your fix (commit 302661356086d8f0e2eb50c72b2b24130197df9a), there is a conflict of Approval Screen and Welcome message (during first login). So with your fix, user will no longer see the Welcome message. Can you please take a look?

**Comment by davidnhtd** [comment]
> @patricijab on your fix (commit [3026613](https://github.com/WomenPlusPlus/deploy-impact-21-inzone-b/commit/302661356086d8f0e2eb50c72b2b24130197df9a)), there is a conflict of Approval Screen and Welcome message (during first login). So with your fix, user will no longer see the Welcome message. Can you please take a look?

This is fixed from the backend to set the flag "first_query_done" properly
