### ISSUE TITLE
As a student, when I start the exam, the tab-changing detection will be activated, as part of the anti-cheating mechanism.

### ISSUE THREAD

**Issue by davidnhtd** [WomenPlusPlus/deploy-impact-21-inzone-b#136]
Acceptance criteria:
- the detection activated only after a student starts the exam (aka start seeing the first question)
- the detection is de-activated after a student submits or goes to another page

**Comment by Brandi-Revels** [comment]
**Notes from Chris:**

Parse can save the exam state in local storage
Lou confirmed the saving of user progress is more important than the anti-cheating mechanisms
