### ISSUE TITLE
As a student, when I start the exam, the onblur event of the browser will be activated, as part of the anti-cheating mechanism.

### ISSUE THREAD

**Issue by davidnhtd** [WomenPlusPlus/deploy-impact-21-inzone-b#137]
Acceptance criteria:
- onblur event activated only after a student starts the exam (aka start seeing the first question)
- onblur even is de-activated after a student submits or goes to another page

*** Finally focus and visibility api instead of onblur.

**Comment by Brandi-Revels** [comment]
**Notes from Chris:**

Parse can save the exam state in local storage
Lou confirmed the saving of user progress is more important than the anti-cheating mechanisms
