### ISSUE TITLE
As a student, during submission of answers (at the end or automatically), if there is no internet connection, I will be asked to press submit again, until successful

### ISSUE THREAD

**Issue by davidnhtd** [WomenPlusPlus/deploy-impact-21-inzone-b#139]
Acceptance criteria:
- If the submission fails, the student will be notified ("your submission has failed, please retry...") and will be ask to press the submit button again

**Comment by Brandi-Revels** [comment]
**From Chris**

Parse can save the exam state in local storage
Lou confirmed the saving of user progress is more important than the anti-cheating mechanisms
