### ISSUE TITLE
As a student, as part of the anti-cheating, I can only take the exam once

### ISSUE THREAD

**Issue by davidnhtd** [WomenPlusPlus/deploy-impact-21-inzone-b#146]
Acceptance criteria:
- From dashboard, I can view and click the button start an exam if it is assigned to me
- After taking the exam, from the dashboard, I can no longer see the button for the exam I have already taken before

**Comment by AntoninaZubach** [comment]
Now starting exam is not possible if it's already started.  See commit: "Add routes: POST /exam, PUT /exam/<id>/startExam, DELETE /exam/<id>" in origin/backend_exam.
