### ISSUE TITLE
Update GET student/{email}/current-exams to only return exam which has not taken before

### ISSUE THREAD

**Issue by davidnhtd** [WomenPlusPlus/deploy-impact-21-inzone-b#148]
This should return exams which:
1. start time < current time (which is the current logic)
2. close time > current time (which is the current logic)
3. taken time is null

**Comment by AntoninaZubach** [comment]
Resolved in commit "Update GET student/{email}/current-exams to only return exam which has not taken before" in origin/backend_exam
