### ISSUE TITLE
The notification of timeout, cheating and exam-completion overwrite each other

### ISSUE THREAD

**Issue by davidnhtd** [WomenPlusPlus/deploy-impact-21-inzone-b#158]
For example: cheating detected and the notification modal is showing **"we detected that you cheated. Make sure you submit your exam with an internet connection, otherwise your score will be a 0."** , but the clock continues to run, and when the time runs out, the notification modal changes to **"Time's up. Make sure you submit your exam with an internet connection, otherwise your score will be a 0."**
Similarly, if the student completes the exam, the modal is showing "You have completed your MCQ exam! All your answers have been saved ...", but if the time runs out, the modal changes to ***"Time's up. Make sure you submit your exam with an internet connection, otherwise your score will be a 0."****
This is confusing for the student to understand the reason why we ask to submit the answers immediately.
FYI @EzequiasCalvo

**Comment by EzequiasCalvo** [comment]
The first one is solved. Now when you cheated we disable the timer. 
To change the other one I need to know if the modal will be possible to close or we don't want that.
